### PR TITLE
OCPBUGS-16488: rebase to latest upstream master

### PR DESCRIPTION
**Pull request by sjenning**
Reabse on upstream [6395594](https://github.com/kubernetes-sigs/apiserver-network-proxy/commit/6395594767511641c5eedb906b1dc90f38b7914c)

Only two carries remain against upsteam code (not including OWNERS, Dockerfiles, ART stuff)
* load balance traffic across redundant backends https://github.com/openshift/apiserver-network-proxy/pull/6
* Agent: Respect HTTPS_PROXY env vars for proxied connections https://github.com/openshift/apiserver-network-proxy/pull/19

### CODE REVIEW

**Comment by muraee** [comment]
seems you need to run `go mod vendor`

**Review by bryan-cox — APPROVED** [review]
/lgtm

**Pull request merged**
